---
name: lattice

releases:
- name: diego
  version: 0
  url: file:///opt/bosh-provisioner/assets/releases/diego-0.tgz
- name: garden-linux
  version: 0
  url: file:///opt/bosh-provisioner/assets/releases/garden-linux-0.tgz
- name: cf-lattice
  version: 0
  url: file:///opt/bosh-provisioner/assets/releases/cf-lattice-0.tgz

networks:
- name: default
  type: dynamic

update:
  update_watch_time: 60000 - 1200000

compilation:
  network: default

jobs:
- name: lattice-cell
  instances: 1

  networks:
  - name: default

  templates:
  - name: rep
    release: diego
  - name: rootfses
    release: diego

  - name: garden
    release: garden-linux

  - name: consul_agent
    release: cf-lattice
  - name: metron_agent
    release: cf-lattice

properties:
  # For Diego:
  diego:
    ssl:
      skip_cert_verify: true
    rep:
      zone: z1
      bbs:
        api_location: bbs.service.cf.internal:8889
        ca_cert: ""
        client_cert: ""
        client_key: ""
        require_ssl: false

  # For Garden:
  garden:
    disk_quota_enabled: false
    allow_host_access: true # turn off in favor of TCP routing
    persistent_image_list: ["/var/vcap/packages/rootfs_cflinuxfs2/rootfs"]
    enable_graph_cleanup: true

  # For CF:
  nats:
    machines: [placeholder-brain-ip]
    user: nats
    password: nats
  etcd:
    machines: [placeholder-brain-ip]
  metron_agent:
    zone: z1
    deployment: lattice
  consul:
    agent:
      services:
        etcd: {}
        bbs: {}
        auctioneer: {}
        file_server: {}
        ssh_proxy: {}
        gorouter: {}
        receptor: {}
        router_configurer: {}
      servers:
        lan: [placeholder-brain-ip]
    require_ssl: false
  loggregator_endpoint:
    shared_secret: loggregator-secret
